/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: sujirour (https://sketchfab.com/sujirour)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/coconut-tree-d141941578044b0f861ca83b36d4c411
title: Coconut Tree
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CoconutTree(props) {
  const { nodes, materials } = useGLTF("/models/coconut_tree.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.coconut_tree_coconut_tree_mat_0.geometry}
            material={materials.coconut_tree_mat}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/coconut_tree.glb");